### ISSUE TITLE
Make SSH host key persistent

### ISSUE THREAD

**Issue by cityofships** [stackhpc/bastion-terraform#6]

**Comment by brtknr** [comment]
How can this be done?

**Comment by cityofships** [comment]
Cloud-init apparently supports this; I assume the private part would be defined in repository's secrets, with public key stored as a simple plaintext file.

Another option would be to use TF provisioner, probably a bit more complicated to implement.

**Comment by brtknr** [comment]
This seems relevant: https://cloudinit.readthedocs.io/en/latest/topics/modules.html#host-keys

**Comment by brtknr** [comment]
https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/cloudinit_config
https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_instance_v2

**Comment by brtknr** [comment]
TF provisioner may be slightly easier actually as we just need to update the content of the host keys under `/etc/ssh`.
